### ISSUE TITLE
About Data and code

### ISSUE THREAD

**Issue by NaJeehye** [kaist-dmlab/Hi-COVIDNet#7]
At code in main.py, line 60 and line 61 use "Argentina" data. Can I use another country's data?

At code in main.py line 60, 61
    feature_len = train_data_model2[0]['Argentina'].shape[1]
    aux_len = train_data_AUX[0]['Argentina'].shape[0]

**Comment by MinSeok-Pons-Kim** [comment]
Yes, of course. The purpose of the lines are to extract the feature lengths, thus it's possible to use any other countries.
